version: '3'
services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./jeuxdesociete.html:/usr/share/nginx/html/index.html
      - ./css:/usr/share/nginx/html/css
      - ./img:/usr/share/nginx/html/img
    restart: always
