version: "3.9"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=test
      - MYSQL_USER=meriem
      - MYSQL_PASSWORD=test
    volumes:
      - ./mysql-data:/var/lib/mysql
